In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set()

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv', index_col = 'RowNumber')
dataset.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
RowNumber                                                                     
1            15634602  Hargrave          619    France  Female   42       2   
2            15647311      Hill          608     Spain  Female   41       1   
3            15619304      Onio          502    France  Female   42       8   
4            15701354      Boni          699    France  Female   39       1   
5            15737888  Mitchell          850     Spain  Female   43       2   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber                                                        
1               0.00              1          1               1   
2           83807.86              1          0               1   
3          159660.80              3          1               0   
4               0.00              2          0               0   
5          125510.82              1          1               1   

           EstimatedSalary  Exited  
RowNumber                           
1                101348.88       1  
2                112542.58       0  
3                113931.57       1  
4                 93826.63       0  
5                 79084.10       0

In [4]:
X_columns = dataset.columns.tolist()[2:12]
Y_columns = dataset.columns.tolist()[-1:]
print(X_columns)
print(Y_columns)

['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']
['Exited']


In [5]:
X = dataset[X_columns].values
Y = dataset[Y_columns].values

In [6]:
from sklearn.preprocessing import LabelEncoder
X_column_transformer = LabelEncoder()
X[:, 1] = X_column_transformer.fit_transform(X[:, 1])

In [7]:
X[:, 2] = X_column_transformer.fit_transform(X[:, 2])

In [8]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
pipeline = Pipeline(
    [
        ('Categorizer', ColumnTransformer(
            [
                ("Gender Label Encoder", OneHotEncoder(categories = 'auto', drop = 'first'), [2]),
                ("Geography Label Encoder", OneHotEncoder(categories = 'auto', drop = 'first'), [1])
            ],
            remainder = 'passthrough', n_jobs = 1)),
        ('Normalizer', StandardScaler())
    ]
)

In [9]:
X = pipeline.fit_transform(X)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [12]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input

classifier = Sequential()

classifier.add(Dense(units=6, activation='relu', input_dim=X_train.shape[1]))
classifier.add(Dropout(rate=0.1))

In [13]:
classifier.add(Dense(6, activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [14]:
classifier.add(Dense(1, activation = 'sigmoid'))

In [15]:
classifier.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 6)                   │              72 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 6)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 6)                   │              42 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 6)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               7 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 121 (484.00 B)

 Trainable params: 121 (484.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [17]:
history = classifier.fit(X_train, y_train, batch_size = 32, epochs = 200, validation_split = 0.1, verbose = 2)

Epoch 1/200
225/225 - 4s - 19ms/step - accuracy: 0.7876 - loss: 0.5410 - val_accuracy: 0.7950 - val_loss: 0.4673
Epoch 2/200
225/225 - 2s - 7ms/step - accuracy: 0.7956 - loss: 0.4724 - val_accuracy: 0.7950 - val_loss: 0.4491
Epoch 3/200
225/225 - 1s - 3ms/step - accuracy: 0.7954 - loss: 0.4598 - val_accuracy: 0.7950 - val_loss: 0.4383
Epoch 4/200
225/225 - 1s - 2ms/step - accuracy: 0.7958 - loss: 0.4541 - val_accuracy: 0.7950 - val_loss: 0.4320
Epoch 5/200
225/225 - 1s - 3ms/step - accuracy: 0.7958 - loss: 0.4474 - val_accuracy: 0.7950 - val_loss: 0.4274
Epoch 6/200
225/225 - 1s - 3ms/step - accuracy: 0.7960 - loss: 0.4448 - val_accuracy: 0.7950 - val_loss: 0.4250
Epoch 7/200
225/225 - 1s - 3ms/step - accuracy: 0.7960 - loss: 0.4415 - val_accuracy: 0.7950 - val_loss: 0.4212
Epoch 8/200
225/225 - 1s - 3ms/step - accuracy: 0.7961 - loss: 0.4420 - val_accuracy: 0.7950 - val_loss: 0.4193
Epoch 9/200
225/225 - 1s - 3ms/step - accuracy: 0.7961 - loss: 0.4395 - val_accuracy: 0.7950 - val_loss

In [18]:
y_pred = classifier.predict(X_test)
print(y_pred[:5])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0.23211192]
 [0.372856  ]
 [0.23759685]
 [0.08003755]
 [0.20574094]]


In [19]:
y_pred = (y_pred > 0.5).astype(int)
print(y_pred[:5])

[[0]
 [0]
 [0]
 [0]
 [0]]


In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1554   41]
 [ 284  121]]


In [21]:
print(((cm[0][0] + cm[1][1])* 100) / len(y_test), '% of data was classified correctly')

83.75 % of data was classified correctly
